/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

export {
	type ChangeRebaser,
	type FinalChange,
	FinalChangeStatus,
	makeAnonChange,
	mapTaggedChange,
	type RevisionInfo,
	type RevisionMetadataSource,
	type RevisionReplacer,
	type TaggedChange,
	tagChange,
	tagRollbackInverse,
} from "./changeRebaser.js";
export { RevisionTagCodec } from "./revisionTagCodec.js";
export {
	areEqualChangeAtomIdOpts,
	areEqualChangeAtomIds,
	asChangeAtomId,
	type ChangeAtomId,
	type ChangeAtomIdMap,
	type ChangeAtomIdRangeMap,
	type ChangeMetadata,
	type ChangesetLocalId,
	CommitKind,
	type CommitMetadata,
	compareChangesetLocalIds,
	comparePartialChangesetLocalIds,
	comparePartialRevisions,
	type EncodedChangeAtomId,
	type EncodedRevisionTag,
	type EncodedStableId,
	type GraphCommit,
	type LocalChangeMetadata,
	makeChangeAtomId,
	mintCommit,
	newChangeAtomIdRangeMap,
	offsetChangeAtomId,
	type RemoteChangeMetadata,
	type RevisionTag,
	RevisionTagSchema,
	SessionIdSchema,
	StableIdSchema,
	subtractChangeAtomIds,
	taggedAtomId,
	taggedOptAtomId,
} from "./types.js";
export {
	type BranchRebaseResult,
	diffHistories,
	findAncestor,
	findCommonAncestor,
	isAncestor,
	type RebaseStats,
	type RebaseStatsWithDuration,
	rebaseBranch,
	rebaseChange,
	rebaseChangeOverChanges,
	replaceChange,
	revisionMetadataSourceFromInfo,
} from "./utils.js";
