# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# include-publish-npm-package

parameters:
- name: tagName
  type: string

- name: pool
  type: object
  default: Small-eastus2

# Indicates if this build is from a test branch
- name: testBuild
  type: boolean

# Indicates the type of release (if any)
- name: release
  type: string

stages:
- stage: publish_npm_internal_test
  dependsOn: build
  displayName: Publish Internal Test Packages
  condition: and(succeeded(), eq(${{ parameters.testBuild }}, false))
  variables:
  - group: ado-feeds
  jobs:
  - template: /tools/pipelines/templates/include-publish-npm-package-deployment.yml@self
    parameters:
      feedUrl: $(ado-feeds-test) # Comes from the ado-feeds variable group
      feedKind: internal-test
      environment: test-package-build-feed
      pool: ${{ parameters.pool }}

- stage: publish_npm_internal
  dependsOn: build
  displayName: Publish Internal Packages
  condition: and(succeeded(), eq(${{ parameters.testBuild }}, false))
  variables:
  - group: ado-feeds
  jobs:
  - template: /tools/pipelines/templates/include-publish-npm-package-deployment.yml@self
    parameters:
      feedUrl: $(ado-feeds-build)
      feedKind: internal-build
      environment: package-build-feed
      pool: ${{ parameters.pool }}

- stage: publish_npm_official
  dependsOn: build
  displayName: Publish Official Packages
  condition: and(succeeded(), or(eq('${{ parameters.release }}', 'release'), eq('${{ parameters.release }}', 'prerelease')))
  variables:
  - group: ado-feeds
  jobs:
  - template: /tools/pipelines/templates/include-publish-npm-package-deployment.yml@self
    parameters:
      feedKind: public
      feedUrl: https://registry.npmjs.org
      environment: package-npmjs-feed
      pool: ${{ parameters.pool }}
      customEndPoint: npmjs
      tagName: ${{ parameters.tagName }}