/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import type { Metadata } from "next";
// eslint-disable-next-line import/no-internal-modules
import { Inter } from "next/font/google";
import React from "react";
import PageLayout from "@/components/PageLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// eslint-disable-next-line import/no-default-export
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<PageLayout>{children}</PageLayout>
			</body>
		</html>
	);
}
