[package]
name = "sea-webtransport"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[example]]
name = "sea-webtransport-browser"
path = "examples/browser.rs"
crate-type = ["cdylib"]

[dependencies]
bytes.workspace = true
postcard = { version = "1.1.3", features = ["alloc"] }
sea-core = { path = "../sea-core" }
serde = { version = "1.0.219", features = ["derive"] }
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-trait.workspace = true
futures-core.workspace = true
futures-util.workspace = true
tokio.workspace = true
wtransport = "=0.7.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-util.workspace = true
js-sys = "=0.3.105"
sea-memory = { path = "../sea-memory" }
sea-sequencer = { path = "../sea-sequencer" }
wasm-bindgen = "=0.2.128"
wasm-bindgen-futures = "=0.4.78"
web-sys = { version = "=0.3.105", features = [
	"ReadableStream",
	"ReadableStreamDefaultReader",
	"WebTransport",
	"WebTransportBidirectionalStream",
	"WebTransportHash",
	"WebTransportOptions",
	"WebTransportReceiveStream",
	"WebTransportSendStream",
	"WritableStream",
	"WritableStreamDefaultWriter",
] }

[dev-dependencies]
sea-memory = { path = "../sea-memory" }
sea-sequencer = { path = "../sea-sequencer" }

[lints]
workspace = true
