[package]
name = "sea-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
sea-protocol = { path = "../sea-protocol" }
sea-core = { path = "../sea-core" }
thiserror.workspace = true

[dev-dependencies]
sea-service = { path = "../sea-service" }
tokio.workspace = true

[lints]
workspace = true
