[package]
name = "snapshotted-stream-stateful-compression"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
snapshotted-stream-core = { path = "../../snapshotted-stream-core" }
thiserror.workspace = true
zstd = { version = "0.13.3", default-features = false }

[dev-dependencies]
snapshotted-stream-compression = { path = "../snapshotted-stream-compression" }
snapshotted-stream-conformance = { path = "../../snapshotted-stream-conformance" }
snapshotted-stream-memory = { path = "../../snapshotted-stream-memory" }
tokio.workspace = true

[lints]
workspace = true