# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# build-client pipeline

name: $(Build.BuildId)

parameters:
- name: releaseBuildOverride
  displayName: Release Build (default = not released)
  type: string
  default: none
  values:
    - none
    - prerelease
    - release
# Parameter for modifying the 'types' field in the package.json.
# If the value `none` is provided, the 'types' field in package.json will remain unchanged.
- name: packageTypesOverride
  displayName: Change package types (default = none)
  type: string
  default: none
  values:
    - none
    - alpha
    - beta
    # 'public' and 'untrimmed' options have not been fully developed yet
    # - public
    # - untrimmed
- name: publishOverride
  displayName: Publish Override (default = based on branch)
  type: string
  default: default
  values:
    - default
    - skip
    - force
- name: interdependencyRange
  displayName: Range to use for interdependencies (only affects releases) (default = ~)
  type: string
  default: "~"
  # The " " value (a space) is a hacky workaround. ADO doesn't support empty string, but we ultimately use this value as
  # an environment variable in a bash script (the 'update package versions' step), where it gets coerced back to the
  # empty string.
  values:
    - "^"
    - "~"
    - " "
- name: buildToolsVersionToInstall
  displayName: Fluid build tools version (default = installs version in repo)
  type: string
  default: repo

trigger:
  branches:
    include:
    - main
    - next
    - lts
    - release/*
  paths:
    include:
    - .dockerignore
    - .gitattributes
    - .gitignore
    - .gitmodules
    - .git-blame-ignore-revs
    - .markdownlint.json
    - .npmrc
    - .nvmrc
    - .prettierignore
    - .releaseGroup
    - azure
    - biome.json
    - biome.jsonc
    - BREAKING.md
    - common/build/build-common
    - ClientRequirements.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - CredScanSuppressions.json
    - examples
    - experimental
    - fluidBuild.config.cjs
    - layerInfo.json
    - LICENSE
    - NOTICE.md
    - packages
    - PACKAGES.md
    - package.json
    - patches/*
    - pnpm-lock.yaml
    - pnpm-workspace.yaml
    - prettier.config.cjs
    - README.md
    - scripts/*
    - SECURITY.md
    - syncpack.config.cjs
    # markdown-magic is part of the client release group
    - tools/markdown-magic/*
    - tools/pipelines/build-client.yml
    - tools/pipelines/templates/build-npm-client-package.yml
    - tools/pipelines/templates/include-set-package-version.yml
    - tools/pipelines/templates/include-vars.yml
    - tools/pipelines/templates/include-install-pnpm.yml
    - tools/pipelines/templates/include-publish-npm-package.yml
    - tools/pipelines/templates/include-publish-npm-package-deployment.yml
    - tools/pipelines/templates/include-publish-npm-package-steps.yml
    - tools/pipelines/templates/include-git-tag-steps.yml
    - tools/pipelines/templates/include-use-node-version.yml
    - tools/pipelines/templates/include-process-test-results.yml
    - tools/pipelines/templates/include-policy-check.yml
    - tools/pipelines/templates/upload-dev-manifest.yml

pr:
  branches:
    include:
    - main
    - next
    - lts
    - release/*
  paths:
    include:
    - .dockerignore
    - .gitattributes
    - .gitignore
    - .gitmodules
    - .git-blame-ignore-revs
    - .markdownlint.json
    - .npmrc
    - .nvmrc
    - .prettierignore
    - .releaseGroup
    - azure
    - biome.json
    - biome.jsonc
    - BREAKING.md
    - common/build/build-common
    - ClientRequirements.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - CredScanSuppressions.json
    - examples
    - experimental
    - fluidBuild.config.cjs
    - layerInfo.json
    - LICENSE
    - NOTICE.md
    - packages
    - PACKAGES.md
    - package.json
    - patches/*
    - pnpm-lock.yaml
    - pnpm-workspace.yaml
    - prettier.config.cjs
    - README.md
    - scripts/*
    - SECURITY.md
    - syncpack.config.cjs
    # markdown-magic is part of the client release group
    - tools/markdown-magic/*
    - tools/pipelines/build-client.yml
    - tools/pipelines/templates/build-npm-client-package.yml
    - tools/pipelines/templates/include-policy-check.yml
    - tools/pipelines/templates/include-set-package-version.yml
    - tools/pipelines/templates/include-vars.yml
    - tools/pipelines/templates/include-install-pnpm.yml
    - tools/pipelines/templates/include-use-node-version.yml
    - tools/pipelines/templates/include-process-test-results.yml
    - tools/pipelines/templates/upload-dev-manifest.yml

variables:
  - template: /tools/pipelines/templates/include-vars.yml@self
    parameters:
      publishOverride: '${{ parameters.publishOverride }}'
      releaseBuildOverride: '${{ parameters.releaseBuildOverride }}'
  - name: testVariable
    value:  ${{ or(eq(variables['release'], 'release'), eq(variables['release'], 'prerelease')) }}

steps:
  # Echo at runtime
  - script: |
      echo "Runtime value: ${release}"

  # Echo at compile time
  - script: |
      echo "Compile-time value: ${{ variables['release'] }}"
  # Conditional check
  - ${{ if or(eq(variables['release'], 'release'), eq(variables['release'], 'prerelease')) }}:
    - script: |
        echo ${{ variables['testVariable'] }}
      displayName: "Conditional check"
