/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */
import {
	Dropdown,
	IDropdownOption,
	IDropdownStyles,
	IStackTokens,
	Stack,
	StackItem,
} from "@fluentui/react";
import React from "react";

import {
	InboundHandlers,
	ITimestampedTelemetryEvent,
	TelemetryHistoryMessage,
	GetTelemetryHistoryMessage,
	TelemetryEventMessage,
	ISourcedDebuggerMessage,
	handleIncomingMessage,
	postMessagesToWindow,
} from "@fluid-tools/client-debugger";

/**
 * Set the default dislayed size to 100.
 */
const DEFAULT_PAGE_SIZE = 100;

/**
 * Displays telemetry events generated by FluidFramework in the application.
 */
export function TelemetryView(): React.ReactElement {
	const [telemetryEvents, setTelemetryEvents] = React.useState<ITimestampedTelemetryEvent[]>([]);

	React.useEffect(() => {
		/**
		 * Handlers for inbound messages related to telemetry.
		 */
		const inboundMessageHandlers: InboundHandlers = {
			["TELEMETRY_EVENT"]: (untypedMessage) => {
				const message: TelemetryEventMessage = untypedMessage as TelemetryEventMessage;
				setTelemetryEvents((currentEvents) => [...message.data.contents, ...currentEvents]);
				return true;
			},
			["TELEMETRY_HISTORY"]: (untypedMessage) => {
				const message: TelemetryHistoryMessage = untypedMessage as TelemetryHistoryMessage;
				setTelemetryEvents(message.data.contents);
				return true;
			},
		};

		// Event handler for messages coming from the Message Relay
		function messageHandler(event: MessageEvent<Partial<ISourcedDebuggerMessage>>): void {
			handleIncomingMessage(event.data, inboundMessageHandlers);
		}

		globalThis.addEventListener("message", messageHandler);

		// Request all log history
		postMessagesToWindow<GetTelemetryHistoryMessage>(undefined, {
			type: "GET_TELEMETRY_HISTORY",
			data: undefined,
		});
	}, [setTelemetryEvents]);

	return <_TelemetryView telemetryEvents={telemetryEvents}></_TelemetryView>;
}

/**
 * {@link _ListLengthSelectionProps} input props.
 *
 * @internal
 */
export interface _ListLengthSelectionProps {
	/**
	 * The current limit (max number of telemetry events to show).
	 * @defaultValue {@link DEFAULT_PAGE_SIZE}
	 */
	currentLimit: number;

	/**
	 * Called when the selection changes.
	 */
	onChangeSelection(newLimit: number): void;
}

/**
 * A dropdown menu for selecting how many logs to display on the page.
 *
 * @internal
 */
export function _ListLengthSelection(props: _ListLengthSelectionProps): React.ReactElement {
	const { currentLimit, onChangeSelection } = props;
	const dropdownStyles: Partial<IDropdownStyles> = {
		dropdown: { width: "300px", zIndex: "1" },
	};

	const stackTokens: IStackTokens = { childrenGap: 20 };

	// Options formatted for the Fluent Dropdown component
	const dropdownOptions: IDropdownOption[] = [
		{ key: 50, text: "50" },
		{ key: 100, text: "100" },
		{ key: 500, text: "500" },
		{ key: 1000, text: "1000" },
	];

	return (
		<Stack tokens={stackTokens}>
			<div className="list-size-options">
				<h3>Max number of telemetry events to display: </h3>
				<Dropdown
					placeholder="Select an option"
					selectedKey={currentLimit}
					options={dropdownOptions}
					styles={dropdownStyles}
					// change the number of logs displayed on the page
					onChange={(event, option): void => onChangeSelection(option?.key as number)}
				/>
			</div>
		</Stack>
	);
}

/**
 * {@link _TelemetryView} input props.
 *
 * @internal
 */
export interface _TelemetryViewProps {
	telemetryEvents: ITimestampedTelemetryEvent[];
}

/**
 * Debugger view that displays fluid telemetry.
 *
 * @remarks Operates strictly on raw data, so it can be potentially re-used acrossed different contexts.
 *
 * @internal
 */
export function _TelemetryView(props: _TelemetryViewProps): React.ReactElement {
	const { telemetryEvents } = props;
	const [maxEventsToDisplay, setMaxEventsToDisplay] = React.useState<number>(DEFAULT_PAGE_SIZE);
	const filiteredTelemetryEvents =
		telemetryEvents.length > maxEventsToDisplay
			? telemetryEvents.slice(0, maxEventsToDisplay)
			: telemetryEvents;

	function mapEventCategoryToBackgroundColor(eventCategory: string): string {
		switch (eventCategory) {
			case "generic":
				return "#b8ebf2";
			case "performance":
				return "#4cf5a3";
			case "error":
				return "#f54c4f";
			default:
				return "#d2d3d4";
		}
	}

	function replacer(key, value): unknown {
		// Filtering out properties
		if (key === "eventName" || key === "category") {
			return undefined;
		}
		return value;
	}

	const log_view = (
		<div>
			<h3>Telemetry events (newest first):</h3>
			<ul>
				{filiteredTelemetryEvents.map((message, index) => (
					<div
						key={index}
						style={{
							border: "1px solid black",
							backgroundColor: mapEventCategoryToBackgroundColor(
								message.logContent.category,
							),
							padding: "5px",
						}}
					>
						<h4 style={{ margin: "0px" }}>
							EventName: {message.logContent.eventName}
							<br />
							Category: {message.logContent.category}
							<br />
							ContainerId: {message.logContent.containerId} (
							{message.logContent.clientType})
							<br />
							DocumentId: {message.logContent.docId}
							<br />
							Timestamp: {new Date(message.timestamp).toLocaleString()}
							<br />
						</h4>
						<p>{JSON.stringify(message.logContent, replacer, "  ")}</p>
					</div>
				))}
			</ul>
		</div>
	);

	return (
		<Stack>
			<StackItem>
				<_ListLengthSelection
					currentLimit={maxEventsToDisplay}
					onChangeSelection={(key): void => setMaxEventsToDisplay(key)}
				/>
			</StackItem>
			<StackItem>{log_view}</StackItem>
		</Stack>
	);
}
