/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import type { PureDataObject } from "@fluidframework/aqueduct/internal";
import type { IFluidLoadable } from "@fluidframework/core-interfaces";

import { BaseDevtools } from "./BaseDevtools.js";
import type { ContainerKey } from "./CommonInterfaces.js";
import type { DecomposedContainer } from "./DecomposedContainer.js";
import type { ContainerDevtoolsFeatureFlags } from "./Features.js";
import type { InboundHandlers } from "./messaging/index.js";

/**
 * Properties for registering a data object with the Devtools.
 * @alpha
 */
export interface DataObjectProps {
	/**
	 * The data object to register with the Devtools.
	 */
	dataObject: PureDataObject;

	/**
	 * Optional label for the data object replacing the guid generated by {@link @fluidframework/container-runtime#IContainerRuntime.generateDocumentUniqueId}.
	 */
	label?: string;
}

/**
 * Properties for constructing a {@link DataObjectDevtools} instance.
 * @alpha
 */
export interface DataObjectDevtoolsProps {
	/**
	 * The container key to use for this data object.
	 */
	containerKey: ContainerKey;

	/**
	 * The decomposed container wrapping the data object.
	 */
	container: DecomposedContainer;

	/**
	 * (optional) Data associated with the data object.
	 */
	containerData?: Record<string, IFluidLoadable>;
}

/**
 * {@link IContainerDevtools} implementation for data objects.
 *
 * @remarks
 *
 * This class provides devtools functionality for data objects that don't support
 * container-level operations like connect/disconnect/close.
 *
 * @sealed
 */
export class DataObjectDevtools extends BaseDevtools<DecomposedContainer> {
	/**
	 * The registered data object's decomposed container.
	 */
	protected override get container(): DecomposedContainer {
		return this._container;
	}

	private readonly _container: DecomposedContainer;

	public constructor(props: DataObjectDevtoolsProps) {
		// Data objects don't support connection operations, so pass empty handlers
		const specificHandlers: InboundHandlers = {};

		super(props.containerKey, specificHandlers, props.containerData);

		this._container = props.container;

		// Bind container and audience events after container is set
		this.bindContainerEvents();
		this.bindAudienceEvents();
	}

	protected override getSupportedFeatures(): ContainerDevtoolsFeatureFlags {
		return {
			containerDataVisualization: this.containerData !== undefined,
			canModifyContainerState: false,
		};
	}
}
