/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import type { Linter } from "eslint";
import { recommended } from "../../../../common/build/eslint-config-fluid/flat.mts";

const config: Linter.Config[] = [
	...recommended,
	{
		rules: {
			"@fluid-internal/fluid/no-unchecked-record-access": "warn",
			"@rushstack/no-new-null": "off",
			"@typescript-eslint/ban-ts-comment": "off",
			"@typescript-eslint/consistent-type-definitions": "off",
			"@typescript-eslint/consistent-type-exports": "off",
			"@typescript-eslint/consistent-type-imports": "off",
			"@typescript-eslint/dot-notation": "off",
			"@typescript-eslint/explicit-function-return-type": "warn",
			"@typescript-eslint/explicit-module-boundary-types": "off",
			"@typescript-eslint/no-dynamic-delete": "off",
			"@typescript-eslint/no-empty-interface": "off",
			"@typescript-eslint/no-explicit-any": "off",
			"@typescript-eslint/no-invalid-this": "off",
			"@typescript-eslint/no-non-null-assertion": "off",
			"@typescript-eslint/no-require-imports": "off",
			"@typescript-eslint/no-shadow": "off",
			"@typescript-eslint/no-this-alias": "off",
			"@typescript-eslint/no-unnecessary-qualifier": "off",
			"@typescript-eslint/no-unnecessary-type-assertion": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-call": "off",
			"@typescript-eslint/no-unsafe-function-type": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/no-unused-expressions": "off",
			"@typescript-eslint/no-var-requires": "off",
			"@typescript-eslint/prefer-for-of": "off",
			"@typescript-eslint/prefer-includes": "off",
			"@typescript-eslint/prefer-nullish-coalescing": "off",
			"@typescript-eslint/prefer-optional-chain": "off",
			"@typescript-eslint/prefer-readonly": "off",
			"@typescript-eslint/restrict-plus-operands": "off",
			"@typescript-eslint/strict-boolean-expressions": "off",
			"@typescript-eslint/unbound-method": "off",
			"depend/ban-dependencies": [
				"error",
				{
					"allowed": ["lodash", "traverse"],
				},
			],
			"eqeqeq": "off",
			"import-x/no-internal-modules": "off",
			"jsdoc/require-description": "off",
			"no-case-declarations": "off",
			"no-constant-binary-expression": "off",
			"no-inner-declarations": "off",
			"no-multi-spaces": "off",
			"no-param-reassign": "off",
			"no-prototype-builtins": "off",
			"no-restricted-syntax": "off",
			"no-useless-escape": "off",
			"no-var": "off",
			"prefer-arrow-callback": "off",
			"prefer-const": "off",
			"prefer-template": "off",
			"quote-props": "off",
			"tsdoc/syntax": "off",
			"unicorn/better-regex": "off",
			"unicorn/catch-error-name": "off",
			"unicorn/explicit-length-check": "off",
			"unicorn/filename-case": "off",
			"unicorn/new-for-builtins": "off",
			"unicorn/no-array-for-each": "off",
			"unicorn/no-array-reduce": "off",
			"unicorn/no-console-spaces": "off",
			"unicorn/no-lonely-if": "off",
			"unicorn/no-negated-condition": "off",
			"unicorn/no-negation-in-equality-check": "off",
			"unicorn/no-null": "off",
			"unicorn/no-object-as-default-parameter": "off",
			"unicorn/no-thenable": "off",
			"unicorn/no-this-assignment": "off",
			"unicorn/no-typeof-undefined": "off",
			"unicorn/no-useless-promise-resolve-reject": "off",
			"unicorn/no-zero-fractions": "off",
			"unicorn/prefer-default-parameters": "off",
			"unicorn/prefer-export-from": "off",
			"unicorn/prefer-includes": "off",
			"unicorn/prefer-logical-operator-over-ternary": "off",
			"unicorn/prefer-spread": "off",
			"unicorn/prefer-string-slice": "off",
			"unicorn/switch-case-braces": "off",
			"unicorn/throw-new-error": "off",
		},
	},
];

export default config;
