/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 *
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
 */
export declare const pkgName = "@fluidframework/component-runtime";
export declare const pkgVersion = "0.25.0";
//# sourceMappingURL=packageVersion.d.ts.map