[package]
name = "sea-benchmarks"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
bytes.workspace = true
sea-service = { path = "../sea-service" }
sea-protocol = { path = "../sea-protocol" }
sea-webtransport = { path = "../sea-webtransport" }
futures-util.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sea-compression = { path = "../sea-compression" }
sea-core = { path = "../sea-core" }
sea-encryption = { path = "../sea-encryption" }
sea-file = { path = "../sea-file" }
sea-memory = { path = "../sea-memory" }
sea-client = { path = "../sea-client" }
sea-network = { path = "../sea-network" }
sea-stateful-compression = { path = "../sea-stateful-compression" }
tokio.workspace = true
wtransport = "=0.7.2"

[lints]
workspace = true
