/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import {
	type ApiDeclaredItem,
	type ApiItem,
	ApiItemKind,
	type ApiPackage,
	ReleaseTag,
} from "@microsoft/api-extractor-model";

import {
	getApiItemKind,
	getConciseSignature,
	getFileSafeNameForApiItemName,
	getReleaseTag,
	getSingleLineExcerptText,
	getUnscopedPackageName,
	isDeprecated,
	type Mutable,
} from "../../utilities/index.js";
import { createQualifiedDocumentNameForApiItem } from "../ApiItemTransformUtilities.js";

import {
	getHierarchyOptionsWithDefaults,
	type HierarchyConfiguration,
	type HierarchyOptions,
} from "./Hierarchy.js";
import { trimTrailingSemicolon } from "./Utilities.js";

/**
 * Options for configuring the documentation suite generated by the API Item -\> Documentation Domain transformation.
 *
 * @public
 */
export interface DocumentationSuiteConfiguration {
	/**
	 * Whether or not to include a top-level heading in rendered documents.
	 *
	 * @defaultValue `true`
	 *
	 * @remarks If you will be rendering the document contents into some other document content that will inject its
	 * own root heading, this can be used to omit that heading from what is rendered by this system.
	 */
	readonly includeTopLevelDocumentHeading: boolean;

	/**
	 * Whether or not to include a navigation breadcrumb at the top of rendered documents.
	 *
	 * @defaultValue `true`
	 *
	 * @remarks Note: `Model` items will never have a breadcrumb rendered, even if this is specified.
	 */
	readonly includeBreadcrumb: boolean;

	/**
	 * {@link HierarchyConfiguration} to use for the provided API item.
	 */
	readonly hierarchy: HierarchyConfiguration;

	/**
	 * Generate the desired document name for the provided `ApiItem`.
	 *
	 * @remarks Will be invoked for any item configured to generate document or folder level hierarchy via {@link DocumentationSuiteConfiguration.hierarchy}.
	 *
	 * Can be further overridden on a per-item-kind basis via {@link DocumentationSuiteConfiguration.hierarchy}.
	 *
	 * @param apiItem - The API item in question.
	 */
	readonly getDocumentNameForItem: (apiItem: ApiItem) => string;

	/**
	 * Generate the desired folder name for the provided `ApiItem`.
	 *
	 * @remarks Will be invoked for any item configured to generate document or folder level hierarchy via {@link DocumentationSuiteConfiguration.hierarchy}.
	 *
	 * Can be further overridden on a per-item-kind basis via {@link DocumentationSuiteConfiguration.hierarchy}.
	 *
	 * @param apiItem - The API item in question.
	 */
	readonly getFolderNameForItem: (apiItem: ApiItem) => string;

	/**
	 * Optionally provide an override for the URI base used in links generated for the provided `ApiItem`.
	 *
	 * @remarks
	 *
	 * This can be used to match on particular item kinds, package names, etc., and adjust the links generated
	 * in the documentation accordingly.
	 *
	 * @param apiItem - The API item in question.
	 *
	 * @returns The URI base to use for the API item, or undefined if the default base should be used.
	 *
	 * @defaultValue Always use the default URI base.
	 */
	readonly getUriBaseOverrideForItem: (apiItem: ApiItem) => string | undefined;

	/**
	 * Generate heading text for the provided `ApiItem`.
	 *
	 * @param apiItem - The API item for which the heading is being generated.
	 *
	 * @returns The heading title for the API item.
	 *
	 * @defaultValue {@link DefaultDocumentationSuiteConfiguration.defaultGetHeadingTextForItem}
	 */
	readonly getHeadingTextForItem: (apiItem: ApiItem) => string;

	/**
	 * Generate link text for the provided `ApiItem`.
	 *
	 * @param apiItem - The API item for which the link is being generated.
	 *
	 * @returns The text to use in the link to the API item.
	 *
	 * @defaultValue {@link DefaultDocumentationSuiteConfiguration.defaultGetLinkTextForItem}
	 */
	readonly getLinkTextForItem: (apiItem: ApiItem) => string;

	/**
	 * Generate a list of "alerts" to display in API items tables for a given API item.
	 *
	 * @param apiItem - The API item for which table cell contents are being generated.
	 *
	 * @returns The list of "alert" strings to display.
	 *
	 * @defaultValue {@link DefaultDocumentationSuiteConfiguration.defaultGetAlertsForItem}
	 */
	readonly getAlertsForItem: (apiItem: ApiItem) => string[];

	/**
	 * Whether or not the provided `ApiPackage` should be skipped during documentation generation.
	 *
	 * @param apiPackage - The package that may or may not be skipped.
	 *
	 * @returns
	 *
	 * `true` if the package should not be included documentation generation. `false` otherwise.
	 *
	 * @defaultValue No packages are skipped.
	 */
	readonly skipPackage: (apiPackage: ApiPackage) => boolean;

	/**
	 * Minimal release scope to include in generated documentation suite.
	 * API members with matching or higher scope will be included, while lower scoped items will be omitted.
	 *
	 * @remarks
	 *
	 * Note that items tagged as `@internal` are not included in the models generated by API-Extractor,
	 * so `@internal` items will never be included for such models.
	 *
	 * Hierarchy: `@public` \> `@beta` \> `@alpha` \> `@internal`
	 *
	 * @defaultValue Include everything in the input model.
	 *
	 * @example `@beta` and `@public`
	 *
	 * To only include `@beta` and `@public` items (and omit `@alpha` items), specify:
	 *
	 * ```typescript
	 * releaseLevel: ReleaseTag.Beta
	 * ```
	 */
	readonly minimumReleaseLevel?: Exclude<ReleaseTag, ReleaseTag.None>;
}

/**
 * Complete configuration documentation suite generation via the API Item -\> Documentation Domain transformation.
 *
 * @public
 */
export type DocumentationSuiteOptions = Omit<
	Partial<DocumentationSuiteConfiguration>,
	"hierarchy"
> & {
	/**
	 * {@inheritDoc DocumentationSuiteConfiguration.hierarchy}
	 */
	readonly hierarchy?: HierarchyOptions;
};

/**
 * Contains a list of default {@link DocumentationSuiteConfiguration} functions.
 *
 * @public
 */
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace DefaultDocumentationSuiteConfiguration {
	/**
	 * Default {@link DocumentationSuiteConfiguration.getDocumentNameForItem}.
	 *
	 * @remarks
	 * Uses the item's scoped and qualified API name, but is handled differently for the following items:
	 *
	 * - Model: "index"
	 *
	 * - Package: Use the unscoped package name.
	 */
	export function defaultGetDocumentNameForItem(
		apiItem: ApiItem,
		config: DocumentationSuiteConfiguration,
	): string {
		const kind = getApiItemKind(apiItem);
		switch (kind) {
			case ApiItemKind.Model: {
				return "index";
			}
			case ApiItemKind.Package: {
				return getFileSafeNameForApiItemName(getUnscopedPackageName(apiItem as ApiPackage));
			}
			default: {
				return createQualifiedDocumentNameForApiItem(apiItem, config);
			}
		}
	}

	/**
	 * Default {@link DocumentationSuiteConfiguration.getFolderNameForItem}.
	 *
	 * @remarks
	 * Uses the item's scoped and qualified API name, but is handled differently for the  following items:
	 *
	 * - Package: Use the unscoped package name.
	 */
	export function defaultGetFolderNameForItem(
		apiItem: ApiItem,
		config: DocumentationSuiteConfiguration,
	): string {
		const kind = getApiItemKind(apiItem);
		switch (kind) {
			case ApiItemKind.Package: {
				return getFileSafeNameForApiItemName(getUnscopedPackageName(apiItem as ApiPackage));
			}
			default: {
				// Let the system generate a unique name that accounts for folder hierarchy.
				return createQualifiedDocumentNameForApiItem(apiItem, config);
			}
		}
	}

	/**
	 * Default {@link DocumentationSuiteConfiguration.getUriBaseOverrideForItem}.
	 *
	 * Always uses default URI base.
	 */
	export function defaultGetUriBaseOverrideForItem(): string | undefined {
		return undefined;
	}

	/**
	 * Default {@link DocumentationSuiteConfiguration.getHeadingTextForItem}.
	 *
	 * Uses the item's qualified API name, but is handled differently for the following items:
	 *
	 * - CallSignature, ConstructSignature, IndexSignature: Uses a cleaned up variation on the type signature.
	 *
	 * - Model: Uses "API Overview".
	 */
	export function defaultGetHeadingTextForItem(apiItem: ApiItem): string {
		const kind = getApiItemKind(apiItem);
		switch (kind) {
			case ApiItemKind.Model: {
				return "API Overview";
			}
			case ApiItemKind.CallSignature:
			case ApiItemKind.ConstructSignature:
			case ApiItemKind.IndexSignature: {
				// For signature items, the display-name is not particularly useful information
				// ("(constructor)", "(call)", etc.).
				// Instead, we will use a cleaned up variation on the type signature.
				const excerpt = getSingleLineExcerptText((apiItem as ApiDeclaredItem).excerpt);
				return trimTrailingSemicolon(excerpt);
			}
			default: {
				return apiItem.displayName;
			}
		}
	}

	/**
	 * Default {@link DocumentationSuiteConfiguration.getLinkTextForItem}.
	 *
	 * Uses the item's signature, except for `Model` items, in which case the text "Packages" is displayed.
	 */
	export function defaultGetLinkTextForItem(apiItem: ApiItem): string {
		const itemKind = getApiItemKind(apiItem);
		switch (itemKind) {
			case ApiItemKind.Model: {
				return "Packages";
			}
			case ApiItemKind.CallSignature:
			case ApiItemKind.ConstructSignature:
			case ApiItemKind.IndexSignature: {
				// For signature items, the display-name is not particularly useful information
				// ("(constructor)", "(call)", etc.).
				// Instead, we will use a cleaned up variation on the type signature.
				const excerpt = getSingleLineExcerptText((apiItem as ApiDeclaredItem).excerpt);
				return trimTrailingSemicolon(excerpt);
			}
			default: {
				return getConciseSignature(apiItem);
			}
		}
	}

	/**
	 * Default {@link DocumentationSuiteConfiguration.getAlertsForItem}.
	 *
	 * Generates alerts for the following tags, if found:
	 *
	 * - `@alpha`: "Alpha"
	 *
	 * - `@beta`: "Beta"
	 *
	 * - `@deprecated`: "Deprecated"
	 */
	export function defaultGetAlertsForItem(apiItem: ApiItem): string[] {
		const alerts: string[] = [];
		if (isDeprecated(apiItem)) {
			alerts.push("Deprecated");
		}

		const releaseTag = getReleaseTag(apiItem);
		if (releaseTag === ReleaseTag.Alpha) {
			alerts.push("Alpha");
		} else if (releaseTag === ReleaseTag.Beta) {
			alerts.push("Beta");
		}
		return alerts;
	}

	/**
	 * Default {@link DocumentationSuiteConfiguration.skipPackage}.
	 *
	 * Unconditionally returns `false` (i.e. no packages will be filtered out).
	 */
	export function defaultSkipPackage(): boolean {
		return false;
	}
}

/**
 * Gets a complete {@link DocumentationSuiteConfiguration} using the provided partial configuration, and filling
 * in the remainder with the documented defaults.
 */
export function getDocumentationSuiteConfigurationWithDefaults(
	options: DocumentationSuiteOptions,
): DocumentationSuiteConfiguration {
	const hierarchy: HierarchyConfiguration = getHierarchyOptionsWithDefaults(options.hierarchy);

	const config: Mutable<
		Omit<DocumentationSuiteConfiguration, "getDocumentNameForItem" | "getFolderNameForItem">
	> = {
		hierarchy,
		includeTopLevelDocumentHeading: options.includeTopLevelDocumentHeading ?? true,
		includeBreadcrumb: options.includeBreadcrumb ?? true,
		getUriBaseOverrideForItem:
			options.getUriBaseOverrideForItem ??
			DefaultDocumentationSuiteConfiguration.defaultGetUriBaseOverrideForItem,
		getHeadingTextForItem:
			options.getHeadingTextForItem ??
			DefaultDocumentationSuiteConfiguration.defaultGetHeadingTextForItem,
		getLinkTextForItem:
			options.getLinkTextForItem ??
			DefaultDocumentationSuiteConfiguration.defaultGetLinkTextForItem,
		getAlertsForItem:
			options.getAlertsForItem ??
			DefaultDocumentationSuiteConfiguration.defaultGetAlertsForItem,
		skipPackage:
			options.skipPackage ?? DefaultDocumentationSuiteConfiguration.defaultSkipPackage,
		minimumReleaseLevel: options.minimumReleaseLevel ?? ReleaseTag.Internal,
	};

	(config as Mutable<DocumentationSuiteConfiguration>).getDocumentNameForItem =
		options.getDocumentNameForItem ??
		((apiItem) =>
			DefaultDocumentationSuiteConfiguration.defaultGetDocumentNameForItem(
				apiItem,
				config as DocumentationSuiteConfiguration,
			));

	(config as Mutable<DocumentationSuiteConfiguration>).getFolderNameForItem =
		options.getFolderNameForItem ??
		((apiItem) =>
			DefaultDocumentationSuiteConfiguration.defaultGetFolderNameForItem(
				apiItem,
				config as DocumentationSuiteConfiguration,
			));

	return config as DocumentationSuiteConfiguration;
}
