[package]
name = "snapshotted-stream-counter"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
snapshotted-stream-client = { path = "../../crates/sea-client" }
snapshotted-stream-memory = { path = "../../crates/sea-memory" }
tokio.workspace = true

[lints]
workspace = true
