/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

export {};

declare global {
	// Declare global variables for tests. These are set in test/setup.cjs, which
	// is added to required in mocha config, so these variables are available in
	// all test files without needing to import them.
	const nock: typeof import("nock");
	let _: typeof import("lodash");
	const sinon: typeof import("sinon");
	const assert: Chai.AssertStatic;
	const expect: Chai.ExpectStatic;
	const isBrowser: boolean;

	// The generated d.ts files from the .js files in src contain typescript types that are not properly imported.
	// These types are generated by the doc comments, but imports for them are not generated.
	// As these files are currently only consumed by other .js files, these d.ts stubs are enough to make it all work.
	type property = unknown;
	type BaseProperty = unknown;
	type NamedProperty = unknown;
	type NamedNodeProperty = unknown;
}
