# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# include-stage-upload-telemetry

# This template adds a new stage to a pipeline.
# The new stage "targets" another stage (specified as a parameter) and uploads telemetry about that stage to Kusto.

parameters:

# Short description of the telemetry being uploaded. Used as a suffix in the stage ID
# (upload_telemetry_<telemetryDescription>) and shown in the stage display name.
# Must be a valid ADO stage ID component (no spaces or special characters).
- name: telemetryDescription
  type: string

# Stages that must be completed before telemetry can be uploaded.
- name: dependsOn
  type: object
  default: []

# Whether to upload telemetry when a dependency is skipped. Canceled pipelines remain excluded.
# Use this when multiple stages are involved (especially if one might not run if prior fails)
# and telemetry is still desired for failures (which is commonly the case).
- name: runOnSkippedDependencies
  type: boolean
  default: false

# The steps to take after configuring for telemetry upload
- name: telemetry_upload_steps
  type: stepList

stages:
- stage: upload_telemetry_${{ parameters.telemetryDescription }}
  displayName: Upload telemetry to Kusto ('${{ parameters.telemetryDescription }}')
  # Run for all possible pipeline triggers except manual
  # (manual runs tend to be for testing and can fail repeatedly, we don't want that creating incidents)
  ${{ if parameters.runOnSkippedDependencies }}:
    condition: and(not(canceled()), ne(variables['Build.Reason'], 'Manual'))
  ${{ else }}:
    condition: and(succeededOrFailed(), ne(variables['Build.Reason'], 'Manual'))
  dependsOn:
    - ${{ each stage in parameters.dependsOn }}:
      - ${{ stage }}
  jobs:
  - job: upload_run_telemetry
    displayName: Upload telemetry to Kusto
    pool: Small-eastus2
    variables:
    - group: ado-feeds

    steps:
    - checkout: ff_pipeline_host
      path: $(FFPipelineHostDirectory)

    - template: /tools/pipelines/templates/include-use-node-version.yml@self

    - template: /tools/pipelines/templates/include-install.yml@self
      parameters:
        buildDirectory: $(FFPipelineHostDirectory)
        primaryRegistry: $(ado-feeds-ff-download-only)

    - ${{ parameters.telemetry_upload_steps }}
