/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

export type { IBlobManagerLoadInfo } from "./blobManager/index.js";
export {
	AllowTombstoneRequestHeaderKey,
	ChannelCollectionFactory,
	detectOutboundReferences,
} from "./channelCollection.js";
export type { ICompressionRuntimeOptions } from "./compressionDefinitions.js";
export { CompressionAlgorithms, disabledCompressionConfig } from "./compressionDefinitions.js";
export {
	agentSchedulerId,
	ContainerRuntime,
	type ContainerRuntimeOptions,
	type ContainerRuntimeOptionsInternal,
	DeletedResponseHeaderKey,
	type IContainerRuntimeOptions,
	type IContainerRuntimeOptionsInternal,
	InactiveResponseHeaderKey,
	type ISummaryRuntimeOptions,
	type LoadContainerRuntimeParams,
	loadContainerRuntime,
	type RuntimeHeaderData,
	TombstoneResponseHeaderKey,
} from "./containerRuntime.js";
export type { IDataStoreAliasMessage } from "./dataStore.js";
export { FluidDataStoreRegistry } from "./dataStoreRegistry.js";
export {
	type GCFeatureMatrix,
	GCNodeType,
	type GCVersion,
	type IGarbageCollectionRuntime,
	type IGCMetadata,
	type IGCNodeUpdatedProps,
	type IGCRuntimeOptions,
	type IGCStats,
	type IMarkPhaseStats,
	type ISweepPhaseStats,
} from "./gc/index.js";
export type {
	ContainerRuntimeAliasMessage,
	ContainerRuntimeDataStoreOpMessage,
	OutboundContainerRuntimeAttachMessage,
	TypedContainerRuntimeMessage,
	UnknownContainerRuntimeMessage,
} from "./messageTypes.js";
export { ContainerMessageType } from "./messageTypes.js";
export { type IChunkedOp, unpackRuntimeMessage } from "./opLifecycle/index.js";
export {
	dataStoreSupportRequirementsForRuntime,
	loaderSupportRequirementsForRuntime,
	runtimeCompatDetailsForDataStore,
	runtimeCompatDetailsForLoader,
	runtimeCoreCompatDetails,
} from "./runtimeLayerCompatState.js";
export {
	currentDocumentVersionSchema,
	DefaultSummaryConfiguration,
	type DocumentSchemaValueType,
	DocumentsSchemaController,
	type EnqueueSummarizeResult,
	type IAckedSummary,
	type IAckSummaryResult,
	type IBaseSummarizeResult,
	type IBroadcastSummaryResult,
	type ICancellableSummarizerController,
	type ICancellationToken,
	type IClientSummaryWatcher,
	type IConnectableRuntime,
	type IContainerRuntimeMetadata,
	type ICreateContainerMetadata,
	type IDocumentSchema,
	type IDocumentSchemaChangeMessageIncoming,
	type IDocumentSchemaChangeMessageOutgoing,
	type IDocumentSchemaCurrent,
	type IDocumentSchemaFeatures,
	type IDocumentSchemaInfo,
	type IdCompressorMode,
	type IEnqueueSummarizeOptions,
	type IFluidDataStoreAttributes0,
	type IFluidDataStoreAttributes1,
	type IFluidDataStoreAttributes2,
	type IGeneratedSummaryStats,
	type IGenerateSummaryTreeResult,
	type INackSummaryResult,
	type IOnDemandSummarizeOptions,
	type IRefreshSummaryAckOptions,
	type IRetriableFailureError,
	type ISerializedElection,
	type ISubmitSummaryOpResult,
	type ISubmitSummaryOptions,
	type ISummarizeOptions,
	type ISummarizeResults,
	type ISummarizer,
	type ISummarizerInternalsProvider,
	type ISummarizerRuntime,
	type ISummarizingWarning,
	type ISummary,
	type ISummaryAckMessage,
	type ISummaryBaseConfiguration,
	type ISummaryCancellationToken,
	type ISummaryCollectionOpEvents,
	type ISummaryConfiguration,
	type ISummaryConfigurationDisableHeuristics,
	type ISummaryConfigurationDisableSummarizer,
	type ISummaryConfigurationHeuristics,
	type ISummaryConfigurationWithSummaryOnRequest,
	type ISummaryMetadataMessage,
	type ISummaryNackMessage,
	type ISummaryOpMessage,
	type IUploadSummaryResult,
	neverCancelledSummaryToken,
	type OmitAttributesVersions,
	type OpActionEventListener,
	type OpActionEventName,
	type ReadFluidDataStoreAttributes,
	type SubmitSummaryFailureData,
	type SubmitSummaryResult,
	type SummarizeResultPart,
	Summarizer,
	SummaryCollection,
	type SummaryStage,
} from "./summary/index.js";
