/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import { useActiveDocContext } from "@docusaurus/plugin-content-docs/client";
import type { WrapperProps } from "@docusaurus/types";
import type DocsVersionDropdownNavbarItemType from "@theme/NavbarItem/DocsVersionDropdownNavbarItem";
import DocsVersionDropdownNavbarItem from "@theme-original/NavbarItem/DocsVersionDropdownNavbarItem";
import React from "react";

/**
 * Note: this module was generated by `swizzling` the Docusaurus "classic" theme's Footer component.
 *
 * Its inner layout and contents were updated to better suite our needs, but the underlying styling and inner
 * components remain unchanged.
 *
 * See {@link https://docusaurus.io/docs/swizzling/ | here} for more information on swizzling.
 */

/**
 * {@link DocsVersionDropdownNavbarItemWrapper} component props.
 */
type Props = WrapperProps<typeof DocsVersionDropdownNavbarItemType>;

/**
 * Wraps the default DocsVersionDropdownNavbarItem to omit the drop-down on non-versioned pages.
 *
 * @remarks
 * Suggested workaround for lack of version dropdown customization.
 * See {@link https://github.com/facebook/docusaurus/issues/4389}.
 */
export default function DocsVersionDropdownNavbarItemWrapper(props: Props): JSX.Element {
	// Do not display this navbar item if current page is not a doc
	const activeDocContext = useActiveDocContext(props.docsPluginId);
	if (!activeDocContext.activeDoc) {
		return <></>;
	}

	return <DocsVersionDropdownNavbarItem {...props} />;
}
