[package]
name = "snapshotted-stream-content-addressed"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.98.1"

[dependencies]
bytes.workspace = true
sha2 = "0.10.9"
snapshotted-stream-core = { path = "../sea-core" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
