/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 * Generated by "flub generate entrypoints" in @fluidframework/build-tools.
 */
export {
	// Unrestricted APIs
	createIdCompressor, 
	deserializeIdCompressor,
 
	// public APIs
	IIdCompressor, 
	OpSpaceCompressedId, 
	SessionId, 
	SessionSpaceCompressedId, 
	StableId
} from "./index.js";
