name: Update link report
on:
  workflow_run:
    workflows: [ "Website validation" ]
    types:
      - completed

jobs:
  load_report:
    runs-on: ubuntu-latest
    steps:
      - name: Download results
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # pin@v11
        with:
          workflow: website-validation.yml
          # workflow_conclusion: completed
          run_id: ${{ github.event.workflow_run.id }}
          name: website-validation-results
          path: ./results
      - name: Load PR number
        id: load_pr
        run: echo "::set-output name=pr::$(cat pr)"
        working-directory: ./results
      - name: Post report in comment
        uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443 # pin@v2
        with:
          header: linkreport
          recreate: true
          number: ${{ steps.load_pr.outputs.pr }}
          path: ./results/linkcheck
