name: Update link report
on:
  workflow_run:
    workflows: ["Website validation"]
    types:
      - completed

permissions:
  contents: read
  actions: read # for dawidd6/action-download-artifact to query and download artifacts

jobs:
  load_report:
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    steps:
      - name: Download results
        # release notes: https://github.com/dawidd6/action-download-artifact/releases/tag/v11
        uses: dawidd6/action-download-artifact@b6e2e70617bc3265edd6dab6c906732b2f1ae151 # v21
        with:
          workflow: website-validation.yml
          # workflow_conclusion: completed
          run_id: ${{ github.event.workflow_run.id }}
          name: website-validation-results
          path: ./results
      - name: Load PR number
        id: load_pr
        run: echo "pr=$(cat pr)" >> $GITHUB_OUTPUT
        working-directory: ./results
      - name: Post report in comment
        # release notes: https://github.com/marocchino/sticky-pull-request-comment/releases/tag/v3.0.4
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        with:
          header: linkreport
          recreate: true
          number: ${{ steps.load_pr.outputs.pr }}
          path: ./results/linkcheck
