name: "pr-changeset-review"

# This workflow runs lint-like checks against changesets in PRs. The linting tool used is called Vale. The worflow will
# add comments for any warnings or errors that Vale finds in the changeset.

# To run vale locally against changesets, you can use `pnpm run check:changesets`.

on:
  pull_request:
    types:
      - opened # PR is created
      - synchronize # commits added to PR
      - reopened # closed PR re-opened
    branches:
      - main
    paths:
      - ".changeset/**" # Trigger only when changes are found under .changeset

permissions:
  pull-requests: read

jobs:
  vale:
    permissions:
      pull-requests: write # for errata-ai/vale-action to add comments to PRs
    name: vale
    runs-on: ubuntu-latest
    steps:
      # release notes: https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # release notes: https://github.com/errata-ai/vale-action/releases/tag/v2.1.1
      - uses: errata-ai/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff # v3.0.0
        with:
          files: .changeset
          vale_flags: "--glob=*-*-*.md"
          reporter: github-pr-review
          # Only run on added/changed files/lines. See https://github.com/reviewdog/reviewdog#filter-mode
          filter_mode: added
