name: Release branch warning
on:
  pull_request_target:
    types:
      - opened

      # This is triggered when the base branch changes; handles the case where you open a PR against main then change the
      # base branch to a release branch.
      - edited
    branches:
      - release/client/**
      - release/server/**
      - test/release/**

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  warning:
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    steps:
      # release notes: https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: false

      - name: Post warning in comment
        # release notes: https://github.com/marocchino/sticky-pull-request-comment/releases/tag/v3.0.4
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        with:
          header: release-warning
          path: ${{ github.workspace }}/.github/workflows/data/release-branch-warning.md
          only_create: true
