name: Release branch warning
on:
  pull_request_target:
    types:
      - opened

      # This is triggered when the base branch changes; handles the case where you open a PR against main then change the
      # base branch to a release branch.
      - edited
    branches:
      - release/client/**
      - release/server/**
      - test/release/**

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  warning:
    permissions:
      pull-requests: write # for marocchino/sticky-pull-request-comment to create or update PR comment
    runs-on: ubuntu-latest
    steps:
      # release notes: https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
          submodules: false

      - name: Post warning in comment
        # release notes: https://github.com/marocchino/sticky-pull-request-comment/releases/tag/v3.0.4
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # ratchet:marocchino/sticky-pull-request-comment@v3
        with:
          header: release-warning
          path: ${{ github.workspace }}/.github/workflows/data/release-branch-warning.md
          only_create: true
